# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.30.102512'

RELEASE_GIT_HEAD = '9c06a09e22753022cf8fc82ce1194cd133406963'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'OnceUponATimeInAmerica/outia-yt-dlp'

ORIGIN = 'OnceUponATimeInAmerica/outia-yt-dlp'

_pkg_version = '2024.12.30.102512'
